version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-employee
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: son
      MYSQL_PASSWORD: son123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
